version: "3.8"

services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    env_file: ./.env
    command: --init-file /data/application/mysql_init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
      - ./conf/mysql_init.sql:/data/application/mysql_init.sql

  rabbitmq:
    image: rabbitmq:management
    env_file: ./.env
    ports:
      - $RABBITMQ_API_LOCAL_PORT:5672
      - $RABBITMQ_MANAGEMENT_LOCAL_PORT:15672
    volumes:
      - rabbitmq:/var/lib/rabbitmq/
      - ./conf/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./conf/rabbitmq-definition.json:/etc/rabbitmq/definitions.json:ro

volumes:
  db:
  rabbitmq:
