spring:
  datasource:
    url: jdbc:mysql://localhost:3307/petizetest?allowPublicKeyRetrieval=true&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: app
    password: appapp
app:
  queues:
    alterarStatusPedido: pedido_statuspedido_update
